### ISSUE TITLE
feat(frontend): Enterキーで回答を提出

### ISSUE THREAD

**Issue by rdrgn** [ShopOne/Shitforces#113]
現状ではテキストボックスに入力した回答を提出するには、ボタンをクリック（またはTab → Enter）しなければなりません。コンテスト中には、素早く回答を提出できないことに煩わしさを感じます。

変更案
- Enterで提出できるようにする。
  - 誤提出してペナルティを受けるのは嫌。
- Ctrl + Enterで提出できるようにする。
  - Ctrlを押すのは面倒。

**Comment by rdrgn** [comment]
Enter vs Ctrl + Enter についての意見を募集しています。

**Comment by ShopOne** [comment]
Enter だと誤送信がありそうで、ペナ付きコンテストだとつらそうなので Ctrl + Enter 派 です
