### ISSUE TITLE
docs: コンテスト作成方法

### ISSUE THREAD

**Issue by rdrgn** [ShopOne/Shitforces#117]
だいぶ前にTwitterで @ShopOne さんに質問したのに忘れてしまったので、改めて教えていただきたいのですが、聞いて終わりになってドキュメント化されないのは良くないと思ったので、勝手にassignします。

**Comment by rdrgn** [comment]
https://twitter.com/_shop_one/status/1357616154731139075?s=20

> 僕の場合はですが、postgresqlに直接コンソールなどからアクセスしてdbにコンテスト情報等を打ち込んでいます
テーブルの定義はsrc/main/kotlin/com/nazonazo_app/shitforces/ShitforcesApplication.ktの物です

**Comment by rdrgn** [comment]
自分で大体把握できたので、以下のような感じでREADMEに書いておこうと思います。

---

### コンテストの作成

データベースを起動する。

```bash
docker-compose up
```

データベースに接続する。

```bash
psql --host=localhost --port=5432 --username=shop_one db
```

`contestinfo`、`probleminfo`テーブルの構造を表示する。

```
\d contestinfo;
\d probleminfo;
```

コンテスト、問題を作成する。テーブル構造は変更されている可能性があるので、上で表示した構造に合わせてコマンドを変えること。

```
insert into contestinfo (shortname, name, statement, starttime, endtime, contesttype, rated) values ('example', 'コンテスト例', 'コンテスト例です。', current_timestamp, current_timestamp, 'ATCODER', false);
insert into probleminfo (contestname, indexofcontest, point, statement) values ('example', 0, 100, 'A問題です。');
insert into probleminfo (contestname, indexofcontest, point, statement) values ('example', 1, 100, 'B問題です。');
insert into probleminfo (contestname, indexofcontest, point, statement) values ('example', 2, 100, 'C問題です。');
insert into probleminfo (contestname, indexofcontest, point, statement) values ('example', 3, 100, 'D問題です。');
```

追加したコンテスト、問題を表示する。

```
select * from contestinfo;
select * from probleminfo;
```

**Comment by ShopOne** [comment]
反応遅れてごめんなさい…
加えて、problemInfoを見ると問題毎にproblemIdが発行されているのでそのidとanswerInfoを一致察せると答えとなります。
 id | contestId | indexOfContest | point | statement 
 1 | example  | 0                        | 1       | A問題です
となっている時
```
insert into answerInfo(id, answer) values(1, 'A');
insert into answerInfo(id, answer) values(1, 'B');
```
とすると答えになります。

**Comment by rdrgn** [comment]
`java.lang.Error: 不正なコンテスト形式です`と怒られてしまうのですが、`contesttype`の指定の仕方は間違っていますかね……

**Comment by ShopOne** [comment]
あ、ごめんなさい… AtCoderじゃないと動かないかもです…

**Comment by rdrgn** [comment]
(๑>﹏<๑｀)

```kt
    enum class ContestType(val textName: String) {
        ICPC("ICPC"),
        ATCODER("AtCoder"),
        INVALID("INVALID")
    }
```

**Comment by ShopOne** [comment]
たしかtextNameで評価してましたね…
ただ、webからコンテスト作る機構が90%出来たので、さっさとこの辺の仕様に悩まなくて済むようにします…

**Comment by rdrgn** [comment]
すごい

**Comment by rdrgn** [comment]
#124
