### ISSUE TITLE
chore(frontend): Nodeとnpmのバージョンを本番環境に合わせる

### ISSUE THREAD

**Issue by rdrgn** [ShopOne/Shitforces#121]
Nodeとnpmのバージョンに起因する不具合を防止するために、それらを本番環境に合わせたいです。

### 背景

リポジトリにある`package-lock.json`の`lockfileVersion`は`2`だが、Dockerコンテナ内で`npm install`をすると`lockfileVersion`が`1`のファイルが生成し直されていた。おそらくDockerイメージにインストールされているnpmのバージョンが古いためだと考えて`npm install -g npm`で最新のnpmを入れると、今度はアプリが起動しなくなった。

**Comment by rdrgn** [comment]
@ShopOne デプロイ先のNodeとnpmそれぞれのバージョンをお教えください🙇

**Comment by ShopOne** [comment]
node v14.16.0
npm 6.14.11 です
