### ISSUE TITLE
[frontend]ログイン(アカウント)失敗時も成功したとalertが出る

### ISSUE THREAD

**Issue by ShopOne** [ShopOne/Shitforces#134]
誤ったユーザーIDとパスワードの組を入力してもログインに成功しましたと出る。(ログインは出来ずページは遷移しない)
また、既に存在するアカウントIDを入力した場合でもアカウントに作成したとアラートが出る。(実際は成功していない)

**Comment by ShopOne** [comment]
@rdrgn たぶんuseCallBackからのthrow errorが多分上手く行ってないと思うのですが、解決方法分かりますか？

**Comment by rdrgn** [comment]
ひどい不具合だ……調べてみます。
