### ISSUE TITLE
chore(frontend): lockfileVersionを固定する

### ISSUE THREAD

**Issue by rdrgn** [ShopOne/Shitforces#136]
Issue #121 とPR #122 でDocker Compose上の開発環境のnpmのバージョンを固定し、`lockfileVersion`を`1`に変更したものの、Docker Composeを利用していない開発者のnpmのバージョンを固定できておらず、`lockfileVersion`が`2`である`package-lock.json`が再びpushされてしまいました。

改めて`lockfileVersion`を固定する方法を考える必要があります。

選択肢

- Docker Composeで起動したコンテナ内で使用するnpmを最新にする。
  - つまりデプロイ先のバージョンと合わせるのはやめる。
- Docker Composeを利用していない開発者にもnpmのバージョンの固定を強制する。
  - `package.json`の`engines`に書く？
  - 個人的には現実的ではない気がする。

**Comment by ShopOne** [comment]
あー… これはすみません
engineの編集の場合どんな問題が起きそうですかね？

**Comment by rdrgn** [comment]
`engines`への追記はつまり、開発者に特定バージョンのnpmをインストールすることを強制する選択肢ですので、開発者の面倒が増える一因になります。

自分の経験では、npmのバージョンを固定したプロジェクトには遭遇したことがないので、npmは固定しないのが「普通」なのではないかと予想しています。（Nodeのバージョンは固定するのですが……。）実際にはどうなのかわからないので、意見をいただきたいです。

**Comment by ShopOne** [comment]
確かに、同じくバックエンドの方のパッケージ管理のようなことをしているgradleも、ソース内でバージョンについては指定してないですし、しないのが普通なのかもしれません。
なのでnpmを最新にするの方が良さそうな感じはしますね。
