### ISSUE TITLE
rankingのリンク部分の改良

### ISSUE THREAD

**Issue by polyester-CTRL** [ShopOne/Shitforces#148]
rankingの各ページへのリンクを、下の図のAtCoderの順位表のような形にするとデザイン的に良い感じになりそうです。
![順位表 - AtCoder Grand Contest 052 - Google Chrome 2021_04_04 1_01_47 (2)](https://user-images.githubusercontent.com/56536708/113484140-b3cc5f80-94e1-11eb-977e-e93143e74d46.png)

**Comment by ShopOne** [comment]
今のやつは純粋にバグってるのであれですが、ページ数の制限はした方がよさそうですね

**Comment by noyanyan** [comment]
コメントありがとうございます。

やることを明確にするために伺いたいんですが、「AtCoderの順位表のデザイン」って何を指されていますか？
[どのページにも簡単にたどり着ける](https://atcoder.jp/contests/agc050/tasks/agc050_a)ページネーションの実装、リンクを画面の中央に配置するデザイン、あるいはもっと別のデザインのことでしょうか？

**Comment by polyester-CTRL** [comment]
どのページにも簡単にたどり着けるようにしたいというのが意図です。
