### ISSUE TITLE
コンテスト参加履歴の表示

### ISSUE THREAD

**Issue by ShopOne** [ShopOne/Shitforces#149]
コンテスト成績やパフォを表示する
データ自体は accountRatingChangeHistory に入っているので、それをアカウントページの所にタブを一つ生やして、それを取り出す形になると思います。

**Comment by noyanyan** [comment]
とりあえずグラフを作ってみました。レイアウトこんな風でいいですか？
https://codesandbox.io/s/recharts-6x82j?file=/src/App.tsx

**Comment by ShopOne** [comment]
参加履歴の表示なので、グラフより表(A*Coderで言うならコンテスト成績表) のイメージでした。
ただグラフも当然欲しいので、別に issue を生やしておきます。

**Comment by ShopOne** [comment]
#191
