### ISSUE TITLE
[frontend] アカウントページの自分のアカウント名に色が欲しい

### ISSUE THREAD

**Issue by ShopOne** [ShopOne/Shitforces#153]
レート順位表の所にあるアカウント名の色(灰、茶色等)が、アカウントページでも見えるようにしたい。

**Comment by noyanyan** [comment]
やりたいです
ダミーデータがないので、実際にデータが入るとおかしくなるかもしれません。
変更時はReact devtoolsで確認しますが、UIがPR前後で違うようなら遠慮なく指摘してください。

**Comment by ShopOne** [comment]
感謝です！ 宜しくお願いします！

**Comment by ShopOne** [comment]
@noyanyan  そういえば色についてですが、frontend/pages/RankingPage.tsx に色のコードがあると思うので、それを使いつつfunctionsに移してくれると嬉しいです。
