### ISSUE TITLE
feat: 順位表に検索・並べ替えを追加する

### ISSUE THREAD

**Issue by rdrgn** [ShopOne/Shitforces#156]
順位表に検索機能を追加したいです。

しかし、現在のAPIでは順位表をリクエストする際にページを指定できるのみのため、検索処理を実装することができません。これに対する修正は2通り考えられ：
- バックエンドが検索のクエリに対応する。
  - 例 https://atcoder.jp/ranking
- バックエンドは順位表全体を返すように変更する。フロントエンドがクエリに合わせて順位表を加工して表示する。
  - 例 https://atcoder.jp/contests/arc116/standings

個人的には、コンテスト中に使用することを想像すると、検索のたびにレスポンス待ちが発生することのない後者のほうが適しているのかなと思います。

どちらを採用するにもバックエンドの変更が必要なので、 @ShopOne さんに実装方針の相談をしたいです。

**Comment by ShopOne** [comment]
参加者が(今の所)多くて100人程度なので全体送信が大きなコストにならず、僕も後者の方針に賛成です。
そちらの方針で実装してみます。

**Comment by rdrgn** [comment]
わいわい

フロントエンドだけだったらすぐにでもPRを出していたところですが、バックエンドを触らねばならないのでどうにもならず。`api/contests/{contest-id}/ranking`に`page`パラメータを不要にして順位表全体を返すようにする変更をお願いしてもよろしいでしょうか……？

**Comment by ShopOne** [comment]
了解です 一旦それでissueを建てます
ただ仕様としてページ機能を一応残しておきたいので、 page の params が与えられない場合(もしくは null の場合)に順位表全体が返される使用にします。

**Comment by ShopOne** [comment]
nullを与えるとバックエンドのほうが壊れてしまったので、getContestRanking の page に null を与えた場合は順位表全体を返すようにします。

**Comment by rdrgn** [comment]
最終目標
![image](https://user-images.githubusercontent.com/9990535/114268740-b6790880-9a3d-11eb-94a4-0938283ebbbf.png)

**Comment by stmtk1** [comment]
順位表を問題を早く提出した順にソートしたいんですが、正解してない人に対する実装方針が決まりません。
ペナ数が少ない人の方が順位が高いという判定にするだけでいいでしょうか？
ペナ数が同じ場合は実際の順位が高いほうが上にしたほうがよろしいですか？

**Comment by stmtk1** [comment]
また、まだ順位表の中で実装されてない機能はrated対象のみを表示する機能と問題毎にソートする機能だけでしょうか？
