### ISSUE TITLE
コンテスト編集で一部の要素が編集できなくなる

### ISSUE THREAD

**Issue by dem08656775** [ShopOne/Shitforces#162]
コンテスト編集画面で、一部の操作がおかしくなることがある。

【現在確認済み】
・問題文や点数が編集できなくなる
・編集しようとした問題と異なる問題が編集される
・問題が削除できなくなる
・削除しようとした問題と異なる問題が削除される

条件は不明だが、問題を3問以上にしてから、最後の問題以外を削除したり、その後に問題を追加したりするとおかしくなりやすい気がする。

**Comment by ShopOne** [comment]
ありがとうございます。再現が確認できました。
Reactのkeyまわりの使い方を間違えていたっぽいので修正します。

**Comment by ShopOne** [comment]
答えを全部消せてしまったり、popOverがボタン再クリックじゃないと消せなかったりするので、そこも修正します。
