### ISSUE TITLE
feat(frontend): improve the pagination component

### ISSUE THREAD

**Issue by rdrgn** [ShopOne/Shitforces#163]
after #160 

現在存在する`PagingElement`のpropsに`value: number;`を追加し、コンポーネントの外でのstate管理に統一する。

**Comment by rdrgn** [comment]
補足

つまり`PagingElement`のpropsはこういうありふれたパターンに。
```ts
interface Props {
  onChange(value: number): void;
  value: number
  ...
}
```

**Comment by noyanyan** [comment]
やってみました。ちょっと思ってたのと違うとかあれば遠慮なく言ってください。
