### ISSUE TITLE
feat: 順位表のペナルティ入りの最終AC時刻を「分:秒」で表示する

### ISSUE THREAD

**Issue by rdrgn** [ShopOne/Shitforces#170]
各問題のAC時刻が既にそうなっているように、全体の最終AC時刻も「分:秒」に変える。

**Comment by noyanyan** [comment]
やりたいです。最終AC時刻がどこに表示されているかわからないんですが、この画像内（/contest）にありますか？
![image](https://user-images.githubusercontent.com/63000297/115322358-dc7e7580-a1c0-11eb-9131-54a2c174ecc1.png)

**Comment by rdrgn** [comment]
うろ覚えですが、得点の列にある灰色の数が最終AC時刻の「秒」表示になっているので、それに各問題のAC時刻の「分:秒」に使用している関数を噛ませることで実現できると思います。

**Comment by noyanyan** [comment]
ありがとうございます！確認します。
