### ISSUE TITLE
ブラウザから生 TypeScript のソースが見えてしまうのを隠す

### ISSUE THREAD

**Issue by ShopOne** [ShopOne/Shitforces#179]
正直 Github で公開しているのでそこまで大きな影響無いんですが、やっぱりそのまま見えちゃってるのが恥ずかしいのでなんとかしたいです。
ビルドの方法を少し変える必要あり？

**Comment by noyanyan** [comment]
しばらく調べてみましたが、自分はわかりませんでした。`build/`以外を配信しないようにすればいいのかな？と素朴に考えてます。
TypeScriptが確認できるということはクライアントで使われないファイルを配信していることになるので、サーバー代を考えると早めに改善したいですよね。

一応の確認ですが、こちらに参考になる情報はあったりしますか？
https://create-react-app.dev/docs/deployment
https://create-react-app.dev/docs/adding-typescript

**Comment by ShopOne** [comment]
使われないファイルではあるんですが、heroku の課金形態はサーバーの稼働時間(とデータベース)だけなので、あんまり急がなくても大丈夫な案件です。
今の実装では、 create-react-app で build されたソースを バックエンドの Spring の public に渡していて、それを見せている形です。
build.gradle.kts の buildReact のタスクでビルド、その後 frontend の postbuild.js でコピってます。
フロントにあまり詳しくなく、よく調べず使ってたんですが、create-react-app のデフォルトではソースマップを吐き出す設定だったっぽい？です

**Comment by ShopOne** [comment]
上試したらマジでこれだけでした…(草)(草じゃないが)
開発時はソースマップ出して、heroku上ではなんも出さないように環境変数使って書き換えます。
調べていただいてありがとうございますm(_ _)m
