### ISSUE TITLE
[frontend] コンテスト作成時の開始時間、終了時間にテキストボックスを使うのをやめる

### ISSUE THREAD

**Issue by ShopOne** [ShopOne/Shitforces#203]
基本僕(と開発者)しか使わないので実装をサボって放っておいてましたが、直したい部分なので生やしました。

**Comment by ShopOne** [comment]
名前よく知らないですが、TimePicker？とかいうのを使うと良いのかなと思います。

**Comment by noyanyan** [comment]
Reactは仮想DOMを使って差分比較をして、必要な分だけを本当のDOMを編集しているので、直接DOMを操作する系統と相性が悪い可能性があります。仮想DOMでは何も起こってないけど、編集しようとしたら実はこの部分が消えてて操作できないとか。

雑にいうと、考えることが多くなって嫌だなあという気持ちと、もし大変になる要素を許容するならそのリソースを割くのは別のどこかだろうという気持ちです。
参照：[これ](https://qiita.com/mizchi/items/4d25bc26def1719d52e6#%E6%97%A2%E5%AD%98%E3%83%A9%E3%82%A4%E3%83%96%E3%83%A9%E3%83%AA%E3%81%A8%E3%81%AE%E7%9B%B8%E6%80%A7%E3%81%AE%E6%82%AA%E3%81%95) や [これ](
https://qiita.com/seya/items/bbe639a96ea70dcc3e27)

**Comment by noyanyan** [comment]
すこし良さそうなライブラリを調べてみます。

**Comment by noyanyan** [comment]
遅くなりました（三ヶ月！すみません！）が、[datetime-local](https://developer.mozilla.org/ja/docs/Web/HTML/Element/input/datetime-local)に変更するのはどうでしょうか？


# 長所・短所
pros
- カレンダーから選択できるようになる
- Date.parse() ができるため、導入時にロジックへの影響がない
- 一行変更するだけでよい
- ブラウザが実装しているので、個々のライブラリより信頼できる

cons
- 秒までの指定が不可能になる
- アニメーション等がなく、多少ダサい

他の候補として、[@material-ui/pickers](https://material-ui.com/components/pickers/)などがあります。こちらはアニメーションがあり、秒数の指定も可能です。


## 比較画像
右：type="datetime" 左：type="datetime-local"で比較しました。
![image](https://user-images.githubusercontent.com/63000297/126870944-3b2bd701-3bb0-46fb-b146-54853be484c5.png)

**Comment by ShopOne** [comment]
おお〜 ありがとうございます！
ダサさについては、僕しか使わないので大丈夫です 秒数指定もあんまり使う機会ないので良さそうです
