### ISSUE TITLE
他人のアカウントページから自分のアカウントページに移っても他人の参加履歴が表示される

### ISSUE THREAD

**Issue by Udomomo** [ShopOne/Shitforces#244]
# 再現条件
- 自分のアカウントにログインした状態にしておく
- Twitterに投稿されたリンクなどから、他人のアカウントページに行く
- その状態で右上の自分の名前をクリックして自分のアカウントページへ
- 参加履歴をクリックしても、Twitterから遷移した他人の参加履歴のままになっている(その状態で、他人のレーティング数値が載った状態でツイートもできてしまう)

**Comment by ShopOne** [comment]
状況再現出来ました。 ご報告ありがとうございます。

**Comment by noyanyan** [comment]
報告ありがとうございます。

おそらくAccountPage関数のuseEffectが意図と異なる挙動をしてしまっているのが直接の原因だと思います。
```
  const getAccount = useCallback(async() => {
    const accountData = await getAccountInformation(getAccountName())
    // update user info
  }, []);

  useEffect(() => {
    getAccount();
  }, [getAccountName()]);
```
想定する挙動：getAccountNameがユーザー名の変更時にgetAccountを実行し、ユーザー情報を更新すること
実際の挙動：getAccount内においてuseCallbackの第２引数（依存配列）が空配列であるため、getAccountは初回の値のまま再実行される

第２引数にwindow.location.hrefなどを入れれば解決すると思います。

**Comment by noyanyan** [comment]
時間とれそうなので自分で修正します！
