### ISSUE TITLE
(提案)フッター邪魔じゃない？

### ISSUE THREAD

**Issue by ShopOne** [ShopOne/Shitforces#246]
自分であんまり使わないのでわからないんですが、フッター邪魔くさくありませんか？
邪魔くさかったら非表示可能の設定にしたいな〜って思います

**Comment by noyanyan** [comment]
自分は特に気にならないですよ！
ユーザーに聞いてみるのが一番ですが

**Comment by ShopOne** [comment]
邪魔じゃなさそうなので消します
