### ISSUE TITLE
CloudFlare Workersを導入する

### ISSUE THREAD

**Issue by no-yan** [ShopOne/Shitforces#251]
related: #199
APIの取得が遅い要因の一つが、取得先が物理的に遠いことです。エッジキャッシュと呼ばれる技術を導入することで、物理的に近い位置にAPIサーバーのキャッシュをおくことで改善できます。
（自分はサーバーの距離が主要因でサーバーの性能はそこまで問題ではないのではと思っています。herokuはコールドスタートで、どんな小さい処理でもすぐにレスポンスを返さないらしいですが。）

以下のページは、裏でcloudflare workersを使っています。Youtubeと検索してから、一度キャッシュを削除して再度youtubeと検索すると、最初と比べかなり高速に表示されます。別の単語でも同様に高速化されます（無料です）。
https://serverless-api-viewer-c87.pages.dev/

shitforcesでもこれと同様のことをやりたいと考えています。公開して問題ないget系をcloudflare workersに公開すれば、レスポンスが高速化し、サーバーへのリクエストも減るはずです（コスト減）。

## Cloudflare Workers フリープランの制限
一日10万件までということで、問題ないはずです。
### Workers の機能
1 日あたり 100k 件のリクエスト を含む

### リクエストごとに最大 10ms の CPU 時間
最初のリクエスト後の最小遅延
キー バリュー ストレージ機能 2
1 日 10 万回の読み取り操作
1 日 1,000 回の書き込み、削除、リスト操作

## 懸念
もし `:contestId/problems` をcloudflare workersで公開するとなれば、コンテスト開始後即座にキャッシュを更新する必要があります。ここらへんをどうするか考えています。
スケジュールでキャッシュを更新できる機能があるが、これでまかなえるか検証する感じですかね。
まず影響の少なそうな最初の４つで試してみたいです。

- [x] `/api/ranking`
- [x] `/api/account/${accountName}`
- [x] `/api/account/${accountName}/history`
- [x] `/api/contests/latest`

↓公開スケジューリングと高頻度のキャッシュ更新が必要
- [ ] `/api/submissions/${contestId}/raid`
- [ ] `/api/contests/${contestId}`
- [ ] `/api/contests/${contestId}/problems`
- [ ] `/api/contests/${contestId}/standings`

**Comment by noyanyan** [comment]
爆速でかえってくるようになりました
https://myapp.noyan.workers.dev/api/account/noyan

他のユーザーでも一度アクセスすれば、２回目からは高速です
https://myapp.noyan.workers.dev/api/account/anagohirame

**Comment by noyanyan** [comment]
実際にデプロイしてみました。
https://young-basin-03851.herokuapp.com/
一度fetchしたことがあれば、キャッシュを削除しても20ms~60msでfetchできてそうです。


![image](https://user-images.githubusercontent.com/63000297/130363529-9adf0277-fae1-411f-a1d4-052ddbb77ba7.png)


## Cloudflare Workers、導入してみますか？
@ShopOne 
Cloudflare Workersで動くバージョンを作ってみました。これを実際にサービスに採用できるとおもいますか？
勉強がてら作ってみた部分が大きいので（明確な目標とモチベーションがほしかった）、導入できなくても構わないです。

### Cloudflare workersとは
- エッジ（かなり短時間で通信できる）で動くJavaScript
- 役割はコンテンツをキャッシュし、通信を高速化すること

### 採用することのメリット💖
- 高速化による体験の向上 200ms -> 20~40ms 
- サーバーのコスト減
- サーバーの移行などと比べ、失敗時の切り戻しがしやすい(fetchのリンクを戻すだけ)
- 難しさはWorkersの実装内に閉じているので、それ以外は以前と同じように開発できる

### 採用することのデメリット👎
- キャッシュ管理を考える必要がある
　- Cloudflareの独自仕様やCDNへの理解が必要
　- 失敗すると、「いつまでもコンテストが表示されない」など、サービスに直結する事故が起こる
- POST系もキャッシュする場合には、常にキャッシュ事故を警戒する必要がある（e.g. ユーザーの提出履歴　今回はしないし、おそらく今後も必要がない）
- noyanがアクティブでなくなった途端、大きな負債化する恐れがある

**Comment by ShopOne** [comment]
実際サービスのわりには重いので、導入ありかな〜と思います デメリットについても切り替えは用意っぽいので大丈夫だと思います。
お願いしても宜しいでしょうか？

**Comment by noyanyan** [comment]
了解です！ぜひやりましょう。
とりあえずcloudflare workersのアカウントを誰が作るか考えてます（複数アカウントOKか、workerの譲渡が可能か？（無理そう））

**Comment by ShopOne** [comment]
アカウントについては僕がメインで紐付いていた方が良さそうなので僕が作ったほうが良い気もします
共用というとこれですかね？ https://support.cloudflare.com/hc/ja/articles/200167946-Cloudflare%E3%82%A2%E3%82%AB%E3%82%A6%E3%83%B3%E3%83%88%E3%81%B8%E3%81%AE%E3%82%A2%E3%82%AF%E3%82%BB%E3%82%B9%E3%82%92%E7%AE%A1%E7%90%86%E3%81%99%E3%82%8B

**Comment by noyanyan** [comment]
はい、そこでinviteしてもらえれば大丈夫です。アカウントができたら教えて下さい。
いちどdiscordかなにかで一度に作業してもよいのかもしれません。

ここ数週間何も手につかなかったので、かなり間が空いてしまいました。すみません。
