### ISSUE TITLE
PagingElementがバグってる

### ISSUE THREAD

**Issue by ShopOne** [ShopOne/Shitforces#263]
戻るボタンが正しく機能していない
コンテストページからメインページとかに戻ってきたときはちゃんと前見てたページが見れるけど、メインページのままで別ページに行った後、戻るボタンを押してもページが切り替わらない
ついでにURLがキモイ(https://shitforces.herokuapp.com/?page=5 ってなる)のも直したい

**Comment by ShopOne** [comment]
安直にキモイって言ったけど、https://shitforces.herokuapp.com?page=5がたぶん正しいよね

**Comment by noyanyan** [comment]
このonClick関数で履歴管理している部分を、useEffectで管理するようにするといける？
https://github.com/ShopOne/Shitforces/blob/0ecfff3988d678e8dbbb9a92bd24d4ba687a2b8c/frontend/src/components/PagingElement.tsx#L18-L24

**Comment by stmtk1** [comment]
https://stackoverflow.com/questions/39342195/intercept-handle-browsers-back-button-in-react-router 
browserHistory.listenを使えって書かれてるのでやってみようと思います

**Comment by stmtk1** [comment]
https://github.com/ShopOne/Shitforces/pull/261
こちらのイシューで件のコンポーネントを使っているのでマージされ次第修正します
