### ISSUE TITLE
バックエンドのアプデできるライブラリをアップデートしたい

### ISSUE THREAD

**Issue by ShopOne** [ShopOne/Shitforces#264]
フロント、バックエンドともに
バックエンドはテスト部分が少ないし、ライブラリの影響を受けるところは少なさそう
フロントは確認事項が多くて大変そう
#259  はあとまわし

**Comment by ShopOne** [comment]
とりあえずバックエンドだけにしとくか 気持ちはアップデートしたい 気持ちはね

**Comment by stmtk1** [comment]
バックエンドは早めにアップデートしておきたいですね。
