### ISSUE TITLE
フロントエンドの開発用ビルドが内部でプロダクションビルドになっている

### ISSUE THREAD

**Issue by stmtk1** [ShopOne/Shitforces#281]
フロントエンドのビルドが、開発用とプロダクション用に別れているが、開発用の方も、mapを生成しないだけで、内部でプロダクション用のビルドと同じものを作ってるので、実行が遅い。開発用のビルドに書き換えて開発速度を上げたい

**Comment by noyanyan** [comment]
毎回`npm run build`を走らせるから重いということですね。多分gradlewでビルドを実行しているんではないでしょうか？

`npm run start`コマンドで起動すると、編集のたびビルドしなくてよいです。この場合、バックエンド側は`./gradlew bootRun -Pargs="--only-back-end"`で起動させます。

makeファイルにコマンドがあるので、以下のコマンドでも起動できます。
`make back`
`make front`


関連issue: #236

**Comment by stmtk1** [comment]
ありがとうございます。解決しました
