### ISSUE TITLE
colors.jsについての対応

### ISSUE THREAD

**Issue by hayaten0415** [ShopOne/Shitforces#296]
colors.jsについて以下のリンクの通り、悪意のあるバージョンがリリースされています。
frontendディレクトリ配下とルートディレクトリ配下で直接colors.jsは使われていないことは確認しましたが
colors.jsに依存しているパッケージが膨大なため、最悪サーバー停止する必要があるかもしれません。
https://zenn.dev/azu/articles/d56615b2e11ad1

**Comment by hayaten0415** [comment]
colors.jsの直接仕様の結果確認
- masterブランチのソースで確認
```bash
~/Shitforces/frontend$ npm ls colors
frontend@0.1.0 /home/hayaten/Shitforces/frontend
└── (empty)
```
```bash
~/Shitforces$ npm ls colors
/home/hayaten/Shitforces
└── (empty)

```

**Comment by ShopOne** [comment]
連絡ありがとうございます 了解です 再度確認しますが、僕も npm ls でなさそうなのは確認したので大丈夫そうですかね

**Comment by no-yan** [comment]
そのコマンド
`npm ls`は`npm ls --depth=0`と異なり、依存パッケージも探索するという認識です。認識違いがあれば訂正してください。
もしあったとしてセキュリティホール発覚の事例と違い、サーバーではアップデートをしなければパッケージを更新しようがないのでこちらは問題ないという認識ですが、どうなんでしょうか？

**Comment by ShopOne** [comment]
あ、結構最近のアレだったのか…(見てなかったです) その認識で合ってるはずです
