### ISSUE TITLE
refactor(frontend): employ TypeScript

### ISSUE THREAD

**Issue by rdrgn** [ShopOne/Shitforces#39]
JavaScriptのコードをTypeScriptに移行することの提案です。フロントエンドに不慣れであるならばなおさら、型の恩恵は大きいのではないかと思います。

**Comment by ShopOne** [comment]
型があるのは良さそうですね。
TypeScriptの勉強を僕がする必要があるので、少しフロントへのコミットペースは落ちちゃいますが、急いだ開発でも無いので出来ることならやりたいです。

**Comment by ShopOne** [comment]
@rdrgn 勢いでAssigness付けてしまいましたが、こちら対応して頂いても大丈夫ですか？

**Comment by rdrgn** [comment]
👌
