### ISSUE TITLE
[Backend] REST API のパスの再設計

### ISSUE THREAD

**Issue by sei40kr** [ShopOne/Shitforces#47]
リソースベースでREST APIパスを設計すると、同じルールを知ってる開発者から見てパスから役割が分かるので便利です。

有名なガイドラインとして Zalando RESTful API などがあります:
https://restful-api-guidelines-ja.netlify.app

|旧パス|新パス|備考|
|:---|:---|:---|
|`/api/latest-contestInfo`|`GET /api/contests/latest`|イレギュラー, コンテスト名 `latest` を禁止しないと衝突,求いい案|
|`/api/contestInfo`|`GET /api/contests/{contest_id}`||
|`/api/get-contestRanking`|`GET /api/contests/{contest_id}/ranking`||
|`/api/get-submission`|`GET /api/submissions/{submission_id}`||
|`/api/post-submission`|`POST /api/submissions`||
|`/api/problemsInfo`|`GET /api/contests/{contest_id}/problems`||

**Comment by ShopOne** [comment]
apiのルールを決めておくのは良さそうですね、latestはまあlatestなんてコンテストは多分作らないので良いと思います。
