### ISSUE TITLE
[Backend] トランザクション境界の宣言 (@Transactional)

### ISSUE THREAD

**Issue by sei40kr** [ShopOne/Shitforces#53]
トランザクションが宣言されていないので、複数のCRUD操作の途中でエラーが発生すると不整合が発生してしまいます。

Repository を呼び出す `Service` のメソッドに `@Transactional` をつけておくと、そのメソッドで行う DB の操作は必ず全てコミットされるか、全て破棄されるかのどちらかになります。(原子性, atomicity)

**16.5.6 Using @Transactional**
https://docs.spring.io/spring-framework/docs/4.2.x/spring-framework-reference/html/transaction.html#transaction-declarative-annotations

**Comment by ShopOne** [comment]
これは大事ですね、有難うございます(Springに詳しくなくてすみません…)
