### ISSUE TITLE
適切なOGPの設定

### ISSUE THREAD

**Issue by polyester-CTRL** [ShopOne/Shitforces#55]
![shitforces - Google 検索 - Google Chrome 2021_02_05 0_46_17 (2)](https://user-images.githubusercontent.com/56536708/106917667-d47b7180-674b-11eb-9a52-900144f0069f.png)
検索した際に出てくる、現状では「Web site created using create-react-app.」となっている部分を、このサイトについての説明文に変更すると良いのではないでしょうか。

**Comment by ShopOne** [comment]
これGoogle検索で出てくるんですね(びっくり) 直しておきます

**Comment by ShopOne** [comment]
コミット間違えなので再open

**Comment by ShopOne** [comment]
修正するindex.htmlが違うもの(templateの方を修正していた)だったので再オープン
