### ISSUE TITLE
refactor(frontend): rewrite class components with React hooks

### ISSUE THREAD

**Issue by rdrgn** [ShopOne/Shitforces#61]
現行のコードでReactコンポーネントはクラスコンポーネントとして記述されていますが、[hook](https://ja.reactjs.org/docs/hooks-reference.html)を利用しながら関数コンポーネントで記述することで、コードの量を減らしたり、見通しをよくしたりできるのではないかと考えています。

いかがでしょう。

**Comment by ShopOne** [comment]
あまりReactのお作法など詳しくないのですが、やっぱり混在より統一した方が良いのですかね？
した方が良さそうであれば(書きやすいので)関数コンポーネントの方で統一したいと思います。

**Comment by rdrgn** [comment]
クラスコンポーネントでないと対応しづらい場面があれば、適材適所で、混在しても良いと思います。統一することよりも、hookを利用した関数コンポーネントが持つ利点をできるかぎり享受することが目的です。

**Comment by ShopOne** [comment]
なるほど、現時点では必要にかられてクラスコンポーネントにした部分は無いので、今後を考えて今の内に関数コンポーネントに書き換えて良さそうですね。
