### ISSUE TITLE
refactor(frontend): restructure directories in src

### ISSUE THREAD

**Issue by rdrgn** [ShopOne/Shitforces#68]
`*Page`などが散乱していたり、1ファイルに複数コンポーネントが含まれていたりするので、整理しようかなという気持ちになっています。

**Comment by rdrgn** [comment]
@ShopOne 
質問がありまして、既に存在している`share-element`、`share-func`というディレクトリの名称に由来（ベストプラクティス的な知見）はありますか？`coordinate`下のファイルの使い道は何ですか？

**Comment by ShopOne** [comment]
ベストプラクティス的な物はなくて、だいたい適当です(混乱させてごめんなさい…)
coordinateはコンテスト作成用にベースだけ作ったはずなんですが、よくよく見るとContestCoordinatePageと重複していますね…これはひどいです。
coordinateディレクトリは中身ごと削除してしまって良さそうです。

**Comment by rdrgn** [comment]
(๑>﹏<๑｀)

とりあえず、下記のディレクトリでも作りましょうか。`share-func`は扱いを決めかねているので保留……

- `components`（`share-element`をリネーム）
- `pages`

アトミックデザインを採用して、`atoms`、`molecules`、`organisms`、`templates`、`pages`と5層に分けるのも手ですが、このプロジェクトでは過剰かも。
[Atomic Design を分かったつもりになる - DeNA Design](https://design.dena.com/design/atomic-design-%E3%82%92%E5%88%86%E3%81%8B%E3%81%A3%E3%81%9F%E3%81%A4%E3%82%82%E3%82%8A%E3%81%AB%E3%81%AA%E3%82%8B)

どうでしょう。

**Comment by ShopOne** [comment]
はぇ〜 こんなのがあるんですね(ありがとうございます) とはいえたしかに、ここまできっちりしなくても良さそうです。全体的なテーマカラーみたいなのも無いので。
とりあえずはpagesとcomponentsで分けるで良さそうです。
