### ISSUE TITLE
[Bug] 画面左下の順位表更新ボタンを押すと若干バグる

### ISSUE THREAD

**Issue by 1119-2916** [ShopOne/Shitforces#95]
順位表の2ページ目を開いているときに更新を押すと1ページ目の順位表が開かれ順位表のページ数ボタンは 2 のままって感じになります

**Comment by ShopOne** [comment]
ひゃ 本当だ ありがとうございます

**Comment by ShopOne** [comment]
なんかの拍子にこれが直ってました closeします。
